server:
  port: 8086
  servlet:
    context-path: /rest

spring:
  main:
    banner-mode: "off"

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:/test_db;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop

logging:
  level:
    org:
    springframework: ERROR
